version: '3.8'

services:
  # Base de données pour le Sprint 1 (User Management)
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: irrigation_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - irrigo-network

  # Étape 1 : Config Server (Port 8888)
  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - irrigo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      retries: 5

  # Étape 2 : Eureka Server (Port 8761)
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - irrigo-network
  # Étape 3 : User Management Service (Port 8081)
  user-management-service:
    build: ./user-management-service
    container_name: user-management-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/irrigation_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_HOST=eureka-server
    depends_on:
      mysql-db:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - irrigo-network

  # Étape 3 : API Gateway (Port 8080)
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_HOST=eureka-server
    depends_on:
      eureka-server:
        condition: service_started
    networks:
      - irrigo-network

networks:
  irrigo-network:
    driver: bridge

