# Configuration du serveur
server.port=8084

# Configuration Eureka (Découverte de services)
eureka.client.serviceUrl.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/
eureka.instance.prefer-ip-address=true

# Configuration de la sécurité (Facultatif si géré par défaut)
# spring.security.user.name=admin
# spring.security.user.password=admin

# Niveaux de logs pour le débogage des calculs
logging.level.com.irrigo.analyticsservice=DEBUG