server.port=8080

# 1. Connexion à Eureka (Version Docker)
# On utilise le nom du service 'eureka-server' défini dans ton docker-compose
eureka.client.serviceUrl.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/

# 2. Configuration globale de la Gateway
spring.cloud.gateway.discovery.locator.enabled=true

# 3. Route pour le microservice User Management
spring.cloud.gateway.routes[0].id=user-management-service
spring.cloud.gateway.routes[0].uri=lb://user-management-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

# 4. Activation du filtre de sécurité JWT
# C'est ici que la magie opère : toutes les requêtes vers /api/users/ passeront par ton AuthenticationFilter
spring.cloud.gateway.routes[0].filters[0]=AuthenticationFilter