spring.application.name=api-gateway
server.port=8080

# 1. Connexion à Eureka
# Utilise localhost si EUREKA_HOST n'est pas défini (test hors Docker)
eureka.client.serviceUrl.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/
eureka.instance.prefer-ip-address=true

# 2. Configuration globale de la Gateway
spring.cloud.gateway.discovery.locator.enabled=true

# 3. Route pour Microservice User Management (Index 0)
spring.cloud.gateway.routes[0].id=user-management-service
spring.cloud.gateway.routes[0].uri=lb://USER-MANAGEMENT-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[0].filters[0]=AuthenticationFilter

# 4. Route pour Microservice Task Management (Index 1)
spring.cloud.gateway.routes[1].id=task-management-service
spring.cloud.gateway.routes[1].uri=lb://TASK-MANAGEMENT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/tasks/**
spring.cloud.gateway.routes[1].filters[0]=AuthenticationFilter

# 5. Route pour Microservice Weather Intelligence (Index 2)
spring.cloud.gateway.routes[2].id=weather-intelligence-service
spring.cloud.gateway.routes[2].uri=lb://WEATHER-INTELLIGENCE-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/weather/**
# AJOUT : Sécurisation du service météo
spring.cloud.gateway.routes[2].filters[0]=AuthenticationFilter

# Route pour le service d'Analytics
spring.cloud.gateway.routes[3].id=analytics-service
spring.cloud.gateway.routes[3].uri=lb://analytics-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/analytics/**