# Configuration du serveur
# Port 8086 car 8085 est réservé pour le report-service
server.port=8086

# Configuration Eureka (Découverte de services)
eureka.client.serviceUrl.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/
eureka.instance.prefer-ip-address=true

# Clé API Gemini (Indispensable pour le chatbot et l'analyse d'images)
api.gemini.key=${GEMINI_API_KEY}

# Niveaux de logs pour le débogage du bot
logging.level.com.irrigo.botservice=DEBUG

# Configuration pour l'analyse d'images (Multipart)
# Nécessaire pour l'envoi des photos de plantes malades
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB