server.port=8085
spring.application.name=report-service

# Configuration Eureka
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/

# Configuration de la sécurité (si vous utilisez JWT comme dans les autres services)
auth.jwtSecret=votre_cle_tres_secrete_pour_irrigo_ezzayra_solutions_2026_mihoub_ayoub
# auth.jwtExpirationMs=86400000
eureka.instance.prefer-ip-address=true