spring.application.name=config-server
server.port=8888

# Connexion Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Mode Natif : On lit les fichiers dans le dossier "configurations" du classpath
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/configurations