spring.application.name=config-server
server.port=8888

# Connexion Eureka
eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

# Mode Natif : On lit les fichiers dans le dossier "configurations" du classpath
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/configurations